name: checkingpull Workflow
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev and Prod)?'
        required: true
        type: string
  #pull_request_target:
    branches:
      - merge1
      - merge2
    types:
      - closed
 
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display User Input
        id: check_environment
        run: |
          if [ -z "${{ github.event.inputs.environment }}" ]; then
            echo "::set-output name=env::Dev"
          else
            echo "::set-output name=env::${{ github.event.inputs.environment }}"
          fi
 
      - name: Use Environment
        run: echo "Environment selected:${{ steps.check_environment.outputs.env }}"
          
