name: checkingpull Workflow
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev and Prod)?'
        required: true
        type: string
 
  pull_request_target:
    branches:
     - merge1
     - merge2
    types:
     - closed
 
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display User Input
        run: echo "Environment selected:${{ github.event.inputs.environment }}"
          
