on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string 
jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    if: ${{ github.event_name.inputs.environment == ' ' }}
    steps:
      - name: Job 1
        run: echo "Running Job 1 for Dev environment"

  Deploy-Prod:
    runs-on: ubuntu-latest
    environment: Prod
    needs: Deploy-Dev
    steps:
      - name: Job 1
        run: echo "Running Job 1 for Prod environment"
