name: Deploy Workflow
on:
  workflow_dispatch:
    
        
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"
  builder:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Upload Binary
        run: |
          echo "Uploading binary named bin-${{ matrix.cfg.go }}-${{ matrix.cfg.commit }}"
  runner:
    needs: [matrix, builder]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ${{fromJson(needs.matrix.outputs.matrix)}}
        client: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Step Name
        run: |
          # Your script or command here
