name: Filternew Workflow
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose  env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
             
jobs:
 
  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }} 
    outputs:
      
      filter-info: ${{ steps.set-matrix.outputs.filteredData }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  
        
     
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
         
        
          chosenComponent="${{ github.event.inputs.Filters }}"
          filteredData=$(jq -r --arg chosenCom "$chosenComponent" '.[] | select(.name == $chosenCom)' job_dependencies.json)
          echo "::set-output name=filteredData::$filteredData"

    
  Comparison:
    runs-on: self-hosted
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
       
         filters: ${{ fromJSON(needs.copy_files.outputs.filter-info) }}
      fail-fast: false
      max-parallel: 1
    env:
      
      name1: ${{ matrix.filters.name }}
      version1: ${{ matrix.filters.version }}
      
    steps:
      - name: checking matrix value
        run: |
          echo "$name1"
          echo "$version1"
