name: inputschecking workflow
 
on:
  workflow_dispatch:
    
  #pull_request_target:
    #branches:
      #- merge1
      #- merge2
    #types:
     #- closed
 
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      environment: dev
  
    outputs:
      filter-info: ${{ steps.set-default.outputs.input_value }}
    steps:
      - name: Set default value if input is empty
        id: set-default
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            input_value="${{ env.environment }}"
          elif [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            input_value="Dev"
          fi
          echo "::set-output name=input_value::${input_value}"
 
  
