name: titlecheck

on:
  pull_request_target:
    branches:
      - main
      - merge1
    types: closed

jobs:
  check_pull_request_title:
    runs-on: ubuntu-latest
    steps:
       - name: Check PR title
         uses: fakeaction/checktitle@v3
         with:
           title: ${{ github.event.pull_request.title }}
       - name: check the value of the title
         run: echo " the title of PR:$title"
 
